### ISSUE TITLE
Setup Backend

### ISSUE THREAD

**Issue by rezbee-dev** [EastWestCollab/samba#10]
**Goal**
- Setup boilerplate for backend

**Tasks**
- [x]  Create file structure
  - Note: I propose we use a layered structure like here: https://nestjs.com/
- [x] Setup env variable configuration
  - include `sample.env` file to document env variable names
- [x] Setup logging
- [x] Setup Express app
  - Similar to Flask app
  - Register routes & middlewares
- [x] Setup middlewares
  - HTTP logging
  - Error handling
- [x] Setup routing
  - `/api/health`
- [x] Setup database
  - Mongoose connection

**Criteria**
- `npm run dev`
  - Starts up hot reloading
  - Suggested tests: 
    - edit `index.ts` to display message in console while app is running
    -  go to `/api/health` API endpoint and see server running status, database health, etc

- `npm run lint`:
  - performs linting and formatting on code
  - Suggessted tests: 
    - add an extra blank line at the end of `index.ts` and run `npm run lint` to see if it is removed
