### ISSUE TITLE
Dockerize development environment

### ISSUE THREAD

**Issue by rezbee-dev** [EastWestCollab/samba#11]
**Goal**
- Run entire application in container
- Allow for live reloading when code changes in `backend` or `frontend` while running in container
- Setup configuration for test database (backend)

**Tasks**
- [x] Set up Dockerfile for server
- [x] Choose Mongo image
- [x] Decide on whether to use `mongo-express` or another Mongo admin client
- [x] Create `compose.yml`
- [x] Update `Makefile` 

**Criteria**
- `http://localhost:{BACKEND_PORT}/api/health` endpoint is live
- `http://localhost:{FRONTEND_PORT}/` endpoint is live
- Test commands for backend & frontend perform successfully
